services:
    ckfinder.connector.auth:
        class: 'CKSource\Bundle\CKFinderBundle\Authentication\Authentication'
        public: true
        calls:
            - [setContainer, ['@service_container']]

    ckfinder.command.download:
        class: CKSource\Bundle\CKFinderBundle\Command\CKFinderDownloadCommand
        tags:
            - { name: console.command }