services:
    _defaults:
        autowire: true
        autoconfigure: true

    CKSource\Bundle\CKFinderBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'